import type { ManagedPlugin } from './runtime-plugins.ts'
import type { PluginState } from './plugin-state.ts'
import { writeTextFileAtomic } from './text-file.ts'

/** Stable generated-filename inside `<DSH_HOME>/electron/`. */
export const PLUGIN_RUNTIME_CONFIG_FILENAME = 'plugins.cordis.yml'

/** Roster-only composition seam for Electron-managed ecosystem plugins. */
export interface PluginCompositionBackend {
  /** Apply the desired manageable-plugin roster. */
  apply(roster: readonly ManagedPlugin[]): Promise<void>
}

/**
 * Calculate the effective enabled ecosystem plugin roster from inventory and persisted state.
 * @param plugins - Full managed inventory.
 * @param state - Persisted disabled-set state.
 * @returns Enabled manageable plugins in distribution order.
 */
export function effectivePluginRoster(
  plugins: readonly ManagedPlugin[],
  state: PluginState,
): ManagedPlugin[] {
  const disabled = new Set(state.disabled)
  return plugins.filter(plugin => plugin.manageable && !disabled.has(plugin.name))
}

/**
 * Render the generated Cordis include file for Electron-managed ecosystem plugins.
 * @param roster - Enabled manageable plugins in desired order.
 * @returns Deterministic YAML text.
 */
export function renderPluginRuntimeConfig(roster: readonly ManagedPlugin[]): string {
  const lines = [
    '# Generated by DSH Electron.',
    '# Do not edit manually.',
  ]
  if (roster.length === 0) {
    lines.push('[]')
    return `${lines.join('\n')}\n`
  }
  for (const plugin of roster) {
    lines.push(`- id: ${yamlString(plugin.name)}`)
    lines.push(`  name: ${yamlString(plugin.runtimeRequest ?? plugin.name)}`)
  }
  return `${lines.join('\n')}\n`
}

/**
 * Apply desired runtime composition by rewriting the generated include file.
 * @param configPath - Absolute path to `plugins.cordis.yml`.
 * @param roster - Enabled manageable plugins in desired order.
 */
export class DynamicIncludeCompositionBackend implements PluginCompositionBackend {
  constructor(private readonly configPath: string) {}

  async apply(roster: readonly ManagedPlugin[]): Promise<void> {
    await writeTextFileAtomic(this.configPath, renderPluginRuntimeConfig(roster))
  }
}

function yamlString(value: string): string {
  return `'${value.replaceAll("'", "''")}'`
}
